# J-NVM
set style line 1 \
    linecolor rgb '#ff8c00' \
    linetype 1 linewidth 2 \
    pointtype 7 pointsize 1

# FS
set style line 2 \
    linecolor rgb '#4682b4' \
    linetype 1 linewidth 2 \
    pointtype 3 pointsize 1

set style line 3 \
    linecolor rgb '#4682b4' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

# PCJ
set style line 4 \
    linecolor rgb '#5f9ea0' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

set style line 5 \
    linecolor rgb '#a0a0a0' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

set style line 6 \
    linecolor rgb '#c9d0d8' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

# Volatile
set style line 7 \
    linecolor rgb '#49494d' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

# Grayscale (from lighter to darker)
set style line 10 \
    linecolor rgb '#333333' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

set style line 11 \
    linecolor rgb '#666666' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

set style line 12 \
    linecolor rgb '#999999' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1

set style line 13 \
    linecolor rgb '#CCCCCC' \
    linetype 1 linewidth 2 \
    pointtype 5 pointsize 1
